consumes:
- application/json
info:
  description: compliance appliacnation
  title: compliance Application
  version: 1.0.0
produces:
- application/json
schemes:
- http
swagger: "2.0"
definitions:
  createjob:
    type: object
    required:
      - hostname
      - username
      - password
      - compliancetype
    properties:
      id:
        type: string
        minLength: 1
      hostname:
        type: string
        minLength: 1
      username:
        type: string
        minLength: 1
      password:
        type: string
        minLength: 1
      compliancetype:
        type: string
        minLength: 1
  getjob:
    type: object
    properties:
      id:
        type: string
      hostname:
        type: string
      progress:
        type: integer
        format: int
      scanstatus:
        type: string
      compliancetype:
        type: string
      result:
        $ref: '#/definitions/ruleresultarray'
  errorresponse:
    type: object
    required:
      - message
    properties:
      code:
        type: string
      message:
        type: string
  ruleresultarray:
    type: array
    items:
      $ref: '#/definitions/ruleresult'
  ruleresult:
    type: object
    properties:
      rulename:
        type: string
      result:
        type: string
      
paths:
  /:
    post:
      tags:
        - compliance
      operationId: create
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/createjob"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/createjob"
        default:
          description: error
          schema:
            $ref: "#/definitions/errorresponse"
  /{id}:
    parameters:
      - type: string
        name: id
        in: path
        required: true
    get:
      tags:
        - compliance
      responses:
        200:
          description: job progress
          schema:
            $ref: "#/definitions/getjob"
        default:
          description: error
          schema:
            $ref: "#/definitions/errorresponse"

          



